blogger_blog_homepage:
    path:     /
    defaults: { _controller: BloggerBlogBundle:Page:index }

blogger_blog_about:
    path:  /about
    defaults: { _controller: BloggerBlogBundle:Page:about }
    requirements:
        _method:  GET

blogger_blog_contact:
    path:  /contact
    defaults: { _controller: BloggerBlogBundle:Page:contact }
    requirements:
        _method:  GET|POST

blogger_blog_blog_show:
    path:  /{id}/{slug}
    defaults: { _controller: BloggerBlogBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+

blogger_blog_comment_create:
    path:  /comment/{blog_id}
    defaults: { _controller: BloggerBlogBundle:Comment:create }
    requirements:
        _method:  POST
        blog_id: \d+
